### ISSUE TITLE
Unnecessary repository

### ISSUE THREAD

**Issue by petschekr** [GFA-Robotics/Dragonoids-Android-2.35#1]
Hi,

Since I'm still a part of the robotics GitHub organization, I got an email about being subscribed to this repository. I think that the work that you guys are doing for this season should still live in the old repository. Since it was forked from the official FTC implementation, updating to include their new changes is much easier (see [this pull request I made last year](https://github.com/GFA-Robotics/Dragonoids-Android/pull/1)). If you're doing some experimental work, you can also make and checkout a new branch in the main repository and then merge it back into the `master` branch when you feel it's ready for prime time.

Let me know if you have any questions about how to do this.

**Comment by galika1080** [comment]
Ryan,

The new robotics coach wants us to start from scratch, using a new repo for the updated version of the FTC API. We will likely be using certain programs from last year’s repo, but we’re supposed to be working in a new project.

Alex

**Comment by petschekr** [comment]
OK I don't really get that but if she insists you can just work in a branch and set it to track the FTC repo as upstream. You'll want to merge in their changes throughout the season as they make fixes anyway.
